name: CI

on: [push]

jobs:    

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
      - uses: actions/checkout@v1

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        id: hello
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Jay Gould'
      - name: Print previous
        run: echo 'The time was ${{ steps.hello }}.'


  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy website
        uses: jaygould/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: 185.53.173.97
          FTP_USERNAME: subarustage
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          REMOTE_DIR: public_html
          ARGS: --delete
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
