name: Production CI

on:
  push:
    branches:
    - master

jobs:    

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout files
      uses: actions/checkout@v1
    - name: Upload PHP
      uses: actions/upload-artifact@v1
      with:
        name: php-build
        path: vendor
    - if: success()
      name: Send build success message
      run: echo 'success'
    - if: failure()
      name: Send build fail message
      run: echo 'fail'


  test:
    runs-on: ubuntu-latest
    steps:
    - name: Hello world
      uses: actions/hello-world-javascript-action@v1
      with:
        who-to-greet: 'Jay Gould'

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deploy website
      uses: jaygould/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        REMOTE_DIR: public_html
        ARGS: --delete