name: Staging CI

on:
  push:
    branches:
    - staging

jobs:    

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout files
      uses: actions/checkout@v1
    - name: Build PHP
      run: composer update
    - name: Build JS
      run: cd wp-content/themes/boilerplate && npm install && npm run build

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Hello world
      uses: actions/hello-world-javascript-action@v1
      with:
        who-to-greet: 'Jay Gould'

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deploy website
      uses: jaygould/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        REMOTE_DIR: public_html
        ARGS: --delete