name: Staging CI

on:
  push:
    branches:
    - staging

jobs:    

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout files and setup environment
      uses: actions/checkout@v1
      uses: actions/setup-node@v1
      with:
        node-version: '10.15.3'
    - name: Build plugins
      run: composer update
    - name: Upload plugins
      uses: actions/upload-artifact@v1
      with:
        name: plugin-build
        path: vendor
    - name: Build assets
      run: cd wp-content/themes/boilerplate && npm install && npm run build
    - name: Upload assets
      uses: actions/upload-artifact@v1
      with:
        name: js-build
        path: wp-content/themes/boilerplate/scripts
      with:
        name: css-build
        path: wp-content/themes/boilerplate/styles

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Hello world
      uses: actions/hello-world-javascript-action@v1
      with:
        who-to-greet: 'Jay Gould'

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
    - name: Prepare for deployment
      uses: actions/checkout@master
    - name: Download build files
      uses: actions/download-artifact@v1
      with:
        name: plugin-build
      with:
        name: js-build
      with:
        name: css-build
    - name: Deploy website
      uses: jaygould/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        REMOTE_DIR: public_html
        ARGS: --delete